# Creates an entry in html/changelogs automatically, to eventually be compiled by compile_changelogs
name: Auto Changelog
on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
permissions:
  contents: write
jobs:
  auto_changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout
      uses: actions/checkout@v4
<<<<<<< HEAD

    - name: Generate App Token
      id: app-token-generation
      uses: actions/create-github-app-token@v1
      if: env.APP_PRIVATE_KEY != '' && env.APP_ID != ''
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
      env:
        APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        APP_ID: ${{ secrets.APP_ID }}

    - name: Run auto changelog
      uses: actions/github-script@v7
=======
    - name: Run auto changelog
      uses: actions/github-script@v6
>>>>>>> d1ccb530b21a3c41ef5ec37ef5f9330d6e562441
      with:
        script: |
          const { processAutoChangelog } = await import('${{ github.workspace }}/tools/pull_request_hooks/autoChangelog.js')
          await processAutoChangelog({ github, context })
<<<<<<< HEAD
        github-token: ${{ steps.app-token-generation.outputs.token || secrets.GITHUB_TOKEN }}
=======
        github-token: ${{ secrets.COMFY_ORANGE_PAT || secrets.GITHUB_TOKEN }}
>>>>>>> d1ccb530b21a3c41ef5ec37ef5f9330d6e562441
